/**
 * vim: set ts=4 sw=4 tw=99 noet :
 * ======================================================
 * Metamod:Source
 * Copyright (C) 2004-2010 AlliedModders LLC and authors.
 * All rights reserved.
 * ======================================================
 *
 * This software is provided 'as-is', without any express or implied warranty.
 * In no event will the authors be held liable for any damages arising from 
 * the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose, 
 * including commercial applications, and to alter it and redistribute it 
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not 
 * claim that you wrote the original software. If you use this software in a 
 * product, an acknowledgment in the product documentation would be 
 * appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 * misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */

/**
 * @file Contains Metamod version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */
    
#pragma once

#define MMS_BUILD_TAG		"dev"
#define MMS_BUILD_LOCAL_REV	"10"
#define MMS_BUILD_CSET		"b1f9db1"
#define MMS_BUILD_MAJOR		"1"
#define MMS_BUILD_MINOR		"12"
#define MMS_BUILD_RELEASE	"0"

#define MMS_BUILD_UNIQUEID MMS_BUILD_LOCAL_REV ":" MMS_BUILD_CSET

#define MMS_VERSION_STRING	MMS_BUILD_MAJOR "." MMS_BUILD_MINOR "." MMS_BUILD_RELEASE "-" MMS_BUILD_TAG

#define MMS_BUILD_TIMESTAMP	__DATE__ " " __TIME__

# define METAMOD_VERSION 		MMS_VERSION_STRING
# define METAMOD_BUILD_ID		MMS_BUILD_UNIQUEID
# define METAMOD_BUILD_TIME 	MMS_BUILD_TIMESTAMP
